### ISSUE TITLE
Fail to simplify if gltf contain materials

### ISSUE THREAD

**Issue by tom62291** [1147079942/3D-geometry-simplify#5]
Hi, I have tried to use this tools.
This tool is ok when the gltf has no material. But there is bug when the gltf contain materials:

D:\3D-geometry-simplify\src\handler\gltfHandler.js:120
        if (changedBuffer[0].accessor === index) {
                             ^

TypeError: Cannot read property 'accessor' of undefined
    at accessors.forEach (D:\Others\3D-geometry-simplify\src\handler\gltfHandler.js:120:30)
    at Array.forEach (<anonymous>)
    at Object.simplify (D:\Others\3D-geometry-simplify\src\handler\gltfHandler.js:119:15)
    at gltfSimplify (D:\Others\3D-geometry-simplify\src\bin\3DGeometrySimplify.js:58:34)
    at Command.program.command.version.description.action (D:\Others\3D-geometry-simplify\src\bin\3DGeometrySimplify.js:27:9)
    at Command.listener (D:\Others\3D-geometry-simplify\node_modules\commander\index.js:360:8)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (D:\Others\3D-geometry-simplify\node_modules\commander\index.js:799:12)
    at Command.parse (D:\Others\3D-geometry-simplify\node_modules\commander\index.js:563:21)
    at Object.<anonymous> (D:\Others\3D-geometry-simplify\src\bin\3DGeometrySimplify.js:49:9)

**Comment by 1147079942** [comment]
ok,i will check about that,if you can provide your file, it will be very helpful.

**Comment by 1147079942** [comment]
after 1.0.6 the problem is fixed
